### ISSUE TITLE
Remove some tags

### ISSUE THREAD

**Issue by SchrodingerZhu** [SchrodingerZhu/paguroidea#5]
I think there is some ways to reduce the number of tags generated in intermediate procedure:

1. when semi-normalize, `(x ~ y)` or `(x | y)`, we lookahead if `y` is a `ParserRef(z)`, if so, we do not create a new tag for `y`, but leave it as `z`.
2. in the same situation described above, if `y` is `Fixpoint(m, n)`, we can pass tag `m` (and use it for `y`), instead of introducing a new one.

**Comment by SchrodingerZhu** [comment]
@QuarticCat close this?

**Comment by QuarticCat** [comment]
Fixed in #21
